apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 190594267513.dkr.ecr.ap-northeast-2.amazonaws.com/test-api
  newName: 190594267513.dkr.ecr.ap-northeast-2.amazonaws.com/test-api
  newTag: c011b1f3
resources:
- ../../base
patchesStrategicMerge:
- test-deploy-patch.yaml
- test-service-patch.yaml
