apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/test-api
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/test-api
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- test-deploy-patch.yaml
- test-service-patch.yaml